urls:
- url: https://www.cocinadominicana.com/cultura/herencia
  domain: cocinadominicana.com
  name: Cultura y Orígenes
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cultura/tradiciones-costumbres
  domain: cocinadominicana.com
  name: Tradiciones y Costumbres
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cultura/celebraciones
  domain: cocinadominicana.com
  name: Festividades y Celebraciones
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cultura/versus
  domain: cocinadominicana.com
  name: Comparaciones
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cocinar/basicos
  domain: cocinadominicana.com
  name: Cocina Básica
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cocinar/ingredientes
  domain: cocinadominicana.com
  name: Guía de Ingredientes
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cocinar/como-hacer
  domain: cocinadominicana.com
  name: Cómo Hacer
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/cocinar/ideas
  domain: cocinadominicana.com
  name: Ideas de Cocina
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/indice-recetas
  domain: cocinadominicana.com
  name: Indice recetas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/acompanamientos
  domain: cocinadominicana.com
  name: Acompañamientos
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/bebidas
  domain: cocinadominicana.com
  name: Bebidas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/ensaladas
  domain: cocinadominicana.com
  name: Ensaladas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/paletas
  domain: cocinadominicana.com
  name: Paletas y Helados
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/pastelones
  domain: cocinadominicana.com
  name: Pastelones
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/picaderas
  domain: cocinadominicana.com
  name: Picaderas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/platos-principales
  domain: cocinadominicana.com
  name: Platos Principales
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/postres
  domain: cocinadominicana.com
  name: Postres
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/sazones-condimentos
  domain: cocinadominicana.com
  name: Sazones y Condimentos
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/sopas
  domain: cocinadominicana.com
  name: Sopas y Caldos
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/almuerzo
  domain: cocinadominicana.com
  name: Almuerzo
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/cena
  domain: cocinadominicana.com
  name: Cena
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/desayuno
  domain: cocinadominicana.com
  name: Desayuno
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/keto
  domain: cocinadominicana.com
  name: Keto
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/ligera
  domain: cocinadominicana.com
  name: Bajo Calorías
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/libre-gluten
  domain: cocinadominicana.com
  name: Sin Gluten
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/veganas
  domain: cocinadominicana.com
  name: Veganas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/vegetarianas
  domain: cocinadominicana.com
  name: Vegetarianas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/tradiciones-comidas-cuaresma-dominicana
  domain: cocinadominicana.com
  name: Cuaresma
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/invierno
  domain: cocinadominicana.com
  name: Otoño e Invierno
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/navidad
  domain: cocinadominicana.com
  name: Navidad
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/verano
  domain: cocinadominicana.com
  name: Verano y Primavera
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/arroz
  domain: cocinadominicana.com
  name: Arroz
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/auyama
  domain: cocinadominicana.com
  name: Auyama
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas-bacalao-como-cocinar
  domain: cocinadominicana.com
  name: Bacalao
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/batata
  domain: cocinadominicana.com
  name: Batata
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/berenjena-recetas
  domain: cocinadominicana.com
  name: Berenjena
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/carne
  domain: cocinadominicana.com
  name: Carne
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/cerdo
  domain: cocinadominicana.com
  name: Cerdo
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/coco
  domain: cocinadominicana.com
  name: Coco
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/fruta
  domain: cocinadominicana.com
  name: Frutas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/guandules-gandules-recetas
  domain: cocinadominicana.com
  name: Guandules
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/habichuelas
  domain: cocinadominicana.com
  name: Habichuelas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/longaniza
  domain: cocinadominicana.com
  name: Longaniza
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/maiz
  domain: cocinadominicana.com
  name: Maíz
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/mariscos-pescados
  domain: cocinadominicana.com
  name: Mariscos
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/papa
  domain: cocinadominicana.com
  name: Papa
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/pasta
  domain: cocinadominicana.com
  name: Pasta
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/pescado
  domain: cocinadominicana.com
  name: Pescado
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/platano
  domain: cocinadominicana.com
  name: Plátano
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/pollo
  domain: cocinadominicana.com
  name: Pollo
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/res
  domain: cocinadominicana.com
  name: Res
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/salami
  domain: cocinadominicana.com
  name: Salami
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/tayota-recetas-chayote
  domain: cocinadominicana.com
  name: Tayota
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/trigo
  domain: cocinadominicana.com
  name: Trigo
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/recetas/yuca
  domain: cocinadominicana.com
  name: Yuca
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/platos-comida-dominicana
  domain: cocinadominicana.com
  name: Platos Típicos Dominicanos
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/tres-golpes-desayuno-dominicano
  domain: cocinadominicana.com
  name: Desayuno Tradicional Dominicano
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/bandera-dominicana-almuerzo
  domain: cocinadominicana.com
  name: La Bandera Dominicana
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/postres-dominicanos-tradicionales-mas-populares
  domain: cocinadominicana.com
  name: Postres Tradicionales
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/frutas-dominicanas
  domain: cocinadominicana.com
  name: Frutas Dominicanas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/viveres-dominicanos-tuberculos
  domain: cocinadominicana.com
  name: Tubérculos y Víveres
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/hierbas-dominicanas
  domain: cocinadominicana.com
  name: Hierbas Dominicanas
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/6981/especias-cocina-dominicana
  domain: cocinadominicana.com
  name: Especias de la Cocina Dominicana
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/glosario
  domain: cocinadominicana.com
  name: Glosario Culinario
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/inicia
  domain: cocinadominicana.com
  name: Inicia Aquí
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/sobre
  domain: cocinadominicana.com
  name: Sobre Nosotros
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/nuestro-libro
  domain: cocinadominicana.com
  name: Libros
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/mas-populares
  domain: cocinadominicana.com
  name: Más Populares
  processed: true
  max_depth: 2
- url: https://www.cocinadominicana.com/reciente
  domain: cocinadominicana.com
  name: Reciente
  processed: true
  max_depth: 2
- url: http://librosdominicanos.com/
  domain: librosdominicanos.com
  name: Libros Dominicanos
  processed: true
  max_depth: 2
- url: https://poesiadominicana.jmarcano.com/
  domain: poesiadominicana.jmarcano.com
  name: Poesía Dominicana
  processed: true
  max_depth: 2
- url: http://www.los-poetas.com/
  domain: los-poetas.com
  name: Los Poetas
  processed: true
  max_depth: 2
- url: https://www.pucmm.edu.do/biblioteca/recursos-electronicos/e-libros-dominicanos
  domain: pucmm.edu.do
  name: PUCMM E-Libros Dominicanos
  processed: true
  max_depth: 2
- url: https://www.gob.do
  domain: gob.do
  name: Portal Gobierno Central
  processed: true
  max_depth: 2
- url: https://ogtic.gob.do
  domain: ogtic.gob.do
  name: Catálogo Digital de Servicios
  processed: true
  max_depth: 2
- url: https://minpre.gob.do
  domain: minpre.gob.do
  name: Presidencia de la República
  processed: true
  max_depth: 2
- url: https://one.gob.do
  domain: one.gob.do
  name: Oficina Nacional de Estadística
  processed: false
  max_depth: 2
- url: https://economia.gob.do
  domain: economia.gob.do
  name: Ministerio de Economía
  processed: false
  max_depth: 2
- url: https://ministeriodeeducacion.gob.do
  domain: ministeriodeeducacion.gob.do
  name: Ministerio de Educación
  processed: false
  max_depth: 2
- url: https://mirex.gob.do
  domain: mirex.gob.do
  name: Ministerio de Relaciones Exteriores
  processed: false
  max_depth: 2
- url: https://cultura.gob.do
  domain: cultura.gob.do
  name: Ministerio de Cultura
  processed: false
  max_depth: 2
- url: https://mitur.gob.do
  domain: mitur.gob.do
  name: Ministerio de Turismo
  processed: false
  max_depth: 2
- url: https://dgcp.gob.do
  domain: dgcp.gob.do
  name: Presupuesto y Contrataciones
  processed: false
  max_depth: 2
- url: https://bancentral.gov.do
  domain: bancentral.gov.do
  name: Banco Central
  processed: false
  max_depth: 2
- url: https://datos.gob.do
  domain: datos.gob.do
  name: Portal Nacional de Datos Abiertos
  processed: false
  max_depth: 2
- url: https://saip.gob.do
  domain: saip.gob.do
  name: Portal de Transparencia
  processed: false
  max_depth: 2
